### ISSUE TITLE
markmeld doesn't recognize config files with `.yml` extension

### ISSUE THREAD

**Issue by nleroy917** [databio/markmeld#17]
I was trying to use markmeld with a config file named `_markmeld.yml` in the root and I received this error:

```
markmeld.exceptions.ConfigError: You must provide config file or be in a dir with _markmeld.yaml.
```

I know `.yaml` [is preferred](https://stackoverflow.com/a/54265316/13175187) in the community, and I need to be better about naming my yaml files with `.yaml`, but I wonder if maybe `_markmeld.yml` should be accepted too and maybe raise a warning instead?

**Comment by nsheff** [comment]
yeh, you have a good point.

... but I think it's better to be Pythonic and say there's only one way to do it, which prevents confusion (what if someone has both?)

**Comment by nleroy917** [comment]
Thats true

**Comment by nsheff** [comment]
I guess I'm not going to implement this, but if you want to implement this for your own sake then I will merge it in, go for it!
